insert into asset_management.company (name) values('Roadlink');
insert into asset_management.part (name) values('filter');
insert into asset_management.customer (name) values('VikingModum');
insert into asset_management.user (name, email, password) values('Kaur','kaur@gmail.com', 'Kaur123');
insert into asset_management.user (name, email, password) values('Liisa','liisa@gmail.com', 'Liisa123');
insert into asset_management.user (name, email, password) values('Marko','marko@gmail.com', 'Marko123');
insert into asset_management.team (name) values('Team1');
insert into asset_management.team (name) values('Team2');
insert into asset_management.location (name) values('Talli 5');
insert into asset_management.location (name) values('Liivametsa tee 6');
insert into asset_management.operational_status (name, company_id) values('Operational', 1);
insert into asset_management.operational_status (name, company_id) values('Not Operational', 1);